### PR TITLE
Launch

### PR DESCRIPTION
**Pull request by fedderw**

### CODE REVIEW

**Comment by fedderw** [comment]
fixes #64 via Katerina's spreadsheet changes, although open question as to whether or not we're satisfied with how all of it looks/where to use it

**Comment by fedderw** [comment]
Re: both #67 (and #64) 

image
image

**Comment by MaxGhenis** [comment]
Looks great! I'm not attached to sample size in the bubble chart, but could it be added to the small note in the bottom left of the bar chart? e.g. instead of `Country surveyed: USA` it could be `1,204 US respondents` (at some point we could add specificity around voters, likely voters, adults, etc.).

**Comment by fedderw** [comment]
> Looks great! I'm not attached to sample size in the bubble chart, but could it be added to the small note in the bottom left of the bar chart? e.g. instead of `Country surveyed: USA` it could be `1,204 US respondents` (at some point we could add specificity around voters, likely voters, adults, etc.).

Ok cool. Gonna merge this then since these are all small changes otherwise.

**Comment by fedderw** [comment]
also fixed #64, #69

**Comment by MaxGhenis** [comment]
Anything needed on my end to deploy the changes?

**Pull request merged**
